### ISSUE TITLE
Cracked hash in seeker message

### ISSUE THREAD

**Issue by johndpope** [scream314/cicada3301#1]
<img width="1462" alt="Screen Shot 2019-09-26 at 12 07 21 pm" src="https://user-images.githubusercontent.com/289994/65652803-5a66b300-e056-11e9-81f3-a1b2059fe557.png">
<img width="1544" alt="Screen Shot 2019-09-26 at 12 07 46 pm" src="https://user-images.githubusercontent.com/289994/65652804-5c307680-e056-11e9-95af-2dbe66e040b1.png">

36367763ab73783c7af284446c59466b4cd653239a311cb7116d4618dee09a8425893dc7500b464fdaf1672d7bef5e891c6e2274568926a49fb4f45132c2a8b4

https://1711141131131.xyz/

Need to upload the associated mp4 video here

**Comment by scream314** [comment]
Hey @johndpope ,
Thank you for opening this issue.
I am still looking at the authenticity of this, and will update the repo as soon as it turns out to be real.

**Comment by johndpope** [comment]
It's a pity that more work wasn't put into pulling video apart and integrating the content and where that originating. Basically - from what I gather - cicada challenge originates from a mystery school.

**Comment by scream314** [comment]
Sorry.
If you can add anything, feel free to do so.

> pity that more work wasn't put

How do you know how much work was put into this?
It would help a lot, if you could point to a PGP signed message in relation to this.

> Basically - from what I gather - cicada challenge originates from a mystery school.

Can you please link some sources?

**Comment by johndpope** [comment]
it was in the video.
