### ISSUE TITLE
Cicada logo original picture

### ISSUE THREAD

**Issue by scream314** [scream314/cicada3301#11]
I'm not a Photoshop wizard, but I think this matches: https://www.sciencephoto.com/media/135640/view

**Comment by 95111** [comment]
I personally think that its in reverse & that this picture is based on the cicada one. Is there any proof that this picture is around since 2012 or before?

**Comment by scream314** [comment]
> this picture is based on the cicada one

While possible, currently the 2 options are:

A.
 * a professional photographer
 * who published a book about insects in 2009 (https://www.amazon.de/Wunderwelt-Insekten-Meisterhaft-fotografiert-Goetgheluck/dp/3625123681)
 * takes the time and effort to re-create a pixel-perfect 5421 x 3291 pixels big image you can order as a 46.0 x 27.9 cm 300dpi print based on a ~405 x 246 px heavily filtered image
 
B.
* this is the original photo and the Cicada logo is a filtered version

> Is there any proof that this picture is around since 2012 or before?

I just stumbled upon it yesterday, and don't really have the time right now to dig into it, but as the owner of the photo is known it sounds fairly easy to find out.

**Comment by 95111** [comment]
Even if you can't dig in that deep, it's a fairly nice research done here!
But wouldn't go that far to state it as a fact yet

**Comment by RobiereMystere** [comment]
Hello, 
based on this picture
![cicada](https://user-images.githubusercontent.com/68994734/147855409-97fc95c1-5614-4d0b-945b-6606fe9439e9.jpg)

I tried to reproduce the logo. 
here is my recreation :
![Robieres_recreation](https://user-images.githubusercontent.com/68994734/147855424-f67d6022-8d1f-49a0-ae07-5135de6d91be.gif)
 
I think it is another proof that you're right

**Comment by 95111** [comment]
Hello there!
First of all thanks for your effords.
Do you mind sharing the process of how you did this?

**Comment by RobiereMystere** [comment]
Sure !
I used Gimp, playing with brightness-contrast then filter neon. The Logo that is used for the comparison is the Splash from the CicadaOS ( thx @tweqz ). On the "CicadaSolvers" discord, It has been seen that it is a bit different from the original one.
But it may be another topic.
